apiVersion: v1
kind: ConfigMap
metadata:
  # NOTE: This is a generic name that is unique across the cluster.
  # This value MUST not be changed, as it's used by the ClusterPolicy implementation.
  name: organization
  namespace: default
data:
  # TODO: need a org-wide policy and a team policy. team policy only needs the container image?

  #
  # The format version of this configuraiton file.
  format: "v1"

  # Verifier information, i.e., the identify of the entity that created the deploy attestation.
  # `id`:                (Mandatory)  The verifier ID, e.g. 'https://github.com/org/.slsa/workflows/slsa-verifier.yml.'
  # `ref`:               (Optional)   The ref of the verifier, e.g. 'refs/heads/main' or 'refs/tags/v1.2.3'
  # `version`:           (Optional)   The version of the policy, e.g. We recommend following semantic versioning.
  #                                   Use https://kyverno.io/docs/writing-policies/jmespath/#semver_compare if needed.
  # `sigstore_issuer`:   (Mandatory)  The Sigstore issuer.
  # `sigstore_rekor_url`:(Mandatory)  The Sigstore's rekor URL.
  #
  id: "https://github.com/laurentsimon/slsa-policy/.github/workflows/verify-slsa.yml"
  sigstore_issuer: "https://token.actions.githubusercontent.com"
  sigstore_rekor_url: "https://rekor.sigstore.dev"
