name: Deploy echo-server

on:
  workflow_dispatch:
    inputs:
      image:
        description: "The OCI image name. This must not include a tag or digest."
        type: string
      digest:
        description: "The OCI image digest. The image digest of the form '<algorithm>:<digest>' (e.g. 'sha256:abcdef...')"
        type: string
      environment:
        type: choice
        description: Environment to use
        options: 
        - prod
        - dev

permissions: read-all

defaults:
  run:
    shell: bash

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}-echo-server
  REGISTRY_USERNAME: laurentsimon

jobs:
  deploy:
    permissions:
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
      contents: read # To read the repo.
    uses: laurentsimon/slsa-org/.github/workflows/image-deployer.yml@main
    with:
      environment: ${{ inputs.environment }}
      image: ${{ inputs.image }}
      digest: ${{ inputs.digest }}
      # Use name rather than env variable because env are not available for reusable workflows.
      registry-username: laurentsimon
      #registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #registry-password: ${{ secrets.GITHUB_TOKEN }}
